# 10 AI老板人设档案
# today_schedule: 今日日程（模拟从日历/短信/邮件自动抓取）

BOSSES = [
    {
        "id": "boss01",
        "name": "王建国",
        "age": 42,
        "city": "深圳",
        "industry": "企业培训顾问",
        "company_size": "一人公司",
        "annual_revenue": "约80万",
        "wechat_contacts": 600,
        "keywords": ["企业培训", "管理咨询", "HR", "职业技能", "组织发展", "AI培训"],
        "network_type": "企业HR/管理层为主",
        "current_goal": "转型管理咨询，开拓AI培训方向",
        "pain_points": ["前客户3年没联系", "每天刷朋友圈找商机效率极低", "经常忘记跟进报价"],
        "ignore_keywords": ["新能源汽车", "娱乐", "直播带货"],
        "contacts": [
            {"name": "陈总", "role": "上海HR总监", "days_since_contact": 67},
            {"name": "李总", "role": "深圳制造业老板", "days_since_contact": 23},
        ],
        "today_schedule": [
            {"time": "09:00", "title": "跟进上周报价——深圳某科技公司管理培训方案", "type": "跟进", "priority": "高"},
            {"time": "11:00", "title": "准备下周线下课课件（PPT初稿）", "type": "内部任务", "priority": "中"},
            {"time": "14:00", "title": "电话：前同事介绍的新客户初次沟通", "type": "拜访", "priority": "高"},
            {"time": "16:00", "title": "整理上季度回款，催款2笔", "type": "财务", "priority": "中"},
        ],
    },
    {
        "id": "boss02",
        "name": "李晓梅",
        "age": 35,
        "city": "上海",
        "industry": "独立品牌策划顾问",
        "company_size": "一人公司",
        "annual_revenue": "约120万",
        "wechat_contacts": 800,
        "keywords": ["品牌营销", "新消费", "内容策略", "私域运营", "品牌策划"],
        "network_type": "广告/品牌圈",
        "current_goal": "拓展新能源/科技客户，建立AI时代差异化",
        "pain_points": ["业务全靠转介绍但不知道谁能转介绍", "行业动态太多不知道哪些相关", "想拓展新能源客户但不知道切入点"],
        "ignore_keywords": ["制造业", "外贸", "法律"],
        "contacts": [
            {"name": "张总", "role": "新能源公司CMO", "days_since_contact": 45},
            {"name": "王总", "role": "广告公司创始人", "days_since_contact": 12},
        ],
        "today_schedule": [
            {"time": "10:00", "title": "提交某新消费品牌Q2内容策略提案", "type": "截止日", "priority": "高"},
            {"time": "13:00", "title": "午饭：前同事叙旧（广告公司CD）", "type": "社交", "priority": "低"},
            {"time": "15:00", "title": "研究竞品：某科技公司品牌升级案例", "type": "研究", "priority": "中"},
        ],
    },
    {
        "id": "boss03",
        "name": "张伟",
        "age": 38,
        "city": "广州",
        "industry": "外贸公司",
        "company_size": "5人团队",
        "annual_revenue": "约300万",
        "wechat_contacts": 1200,
        "keywords": ["外贸", "跨境电商", "东南亚", "广交会", "汇率", "供应链"],
        "network_type": "海外买家+国内供应商",
        "current_goal": "开拓东南亚市场，参加广交会",
        "pain_points": ["汇率波动影响利润", "东南亚新市场不熟悉", "供应商质量参差不齐"],
        "ignore_keywords": ["娱乐八卦", "国内消费", "律师"],
        "contacts": [
            {"name": "陈老板", "role": "东南亚分销商", "days_since_contact": 30},
            {"name": "供应商李总", "role": "广东制造商", "days_since_contact": 8},
        ],
        "today_schedule": [
            {"time": "08:30", "title": "广交会春季展报名截止——今日必须提交", "type": "截止日", "priority": "高"},
            {"time": "10:00", "title": "越南客户视频会议（订单确认）", "type": "会议", "priority": "高"},
            {"time": "14:00", "title": "审核新供应商样品报告", "type": "内部任务", "priority": "中"},
            {"time": "17:00", "title": "更新阿里国际站产品页面", "type": "运营", "priority": "低"},
        ],
    },
    {
        "id": "boss04",
        "name": "陈思雨",
        "age": 29,
        "city": "成都",
        "industry": "UI/UX设计师",
        "company_size": "一人公司",
        "annual_revenue": "约50万",
        "wechat_contacts": 300,
        "keywords": ["UI设计", "产品设计", "AI工具", "创业公司", "用户体验"],
        "network_type": "互联网/设计圈",
        "current_goal": "进入AI产品设计方向，找到垂直行业定位",
        "pain_points": ["AI工具冲击设计行业", "不知道如何差异化", "客户预算越来越低"],
        "ignore_keywords": ["制造业", "外贸", "金融"],
        "contacts": [
            {"name": "刘总", "role": "成都互联网公司产品总监", "days_since_contact": 15},
            {"name": "赵总", "role": "AI创业公司CEO", "days_since_contact": 90},
        ],
        "today_schedule": [
            {"time": "10:00", "title": "完成某APP首页改版交付（客户验收）", "type": "截止日", "priority": "高"},
            {"time": "14:00", "title": "学习 Figma AI 新功能——自我提升", "type": "学习", "priority": "中"},
            {"time": "20:00", "title": "成都产品设计师线上分享会（线上）", "type": "活动", "priority": "中"},
        ],
    },
    {
        "id": "boss05",
        "name": "刘强",
        "age": 45,
        "city": "北京",
        "industry": "餐饮连锁（4家门店）",
        "company_size": "约50人",
        "annual_revenue": "约800万",
        "wechat_contacts": 500,
        "keywords": ["餐饮", "连锁", "食品安全", "堂食", "外卖", "供应链", "选址"],
        "network_type": "餐饮同行+供应商+商场物业",
        "current_goal": "第5家门店选址，探索预制菜方向",
        "pain_points": ["食材成本上涨", "找不到好选址", "员工流动率高"],
        "ignore_keywords": ["科技", "金融", "外贸"],
        "contacts": [
            {"name": "商场招商张总", "role": "购物中心招商经理", "days_since_contact": 20},
            {"name": "供应商王总", "role": "食材供应商", "days_since_contact": 5},
        ],
        "today_schedule": [
            {"time": "09:00", "title": "西城区某商场选址实地考察", "type": "拜访", "priority": "高"},
            {"time": "12:00", "title": "门店巡检：朝阳店+海淀店", "type": "运营", "priority": "中"},
            {"time": "15:00", "title": "与预制菜供应商初步洽谈", "type": "会议", "priority": "高"},
            {"time": "18:00", "title": "餐饮老板圈子聚餐（朋友邀约）", "type": "社交", "priority": "低"},
        ],
    },
    {
        "id": "boss06",
        "name": "赵敏",
        "age": 33,
        "city": "杭州",
        "industry": "电商卖家（女装）",
        "company_size": "3人团队",
        "annual_revenue": "约200万",
        "wechat_contacts": 400,
        "keywords": ["电商", "女装", "抖音自播", "直播电商", "选款", "供应链", "流量"],
        "network_type": "供应商+主播+电商运营圈",
        "current_goal": "从淘宝转型抖音自播，降低平台依赖",
        "pain_points": ["抖音流量算法不熟悉", "自播投流成本高", "找不到爆款"],
        "ignore_keywords": ["B2B", "制造业", "政策法规"],
        "contacts": [
            {"name": "抖音运营小李", "role": "抖音运营代理", "days_since_contact": 10},
            {"name": "供货商陈总", "role": "女装供应商", "days_since_contact": 3},
        ],
        "today_schedule": [
            {"time": "09:30", "title": "上新春季款——上架30个SKU到抖音小店", "type": "运营", "priority": "高"},
            {"time": "12:00", "title": "直播测试：第一次抖音自播（2小时）", "type": "直播", "priority": "高"},
            {"time": "15:00", "title": "复盘直播数据，调整话术", "type": "复盘", "priority": "中"},
            {"time": "17:00", "title": "与运营小李讨论本周投流方案", "type": "会议", "priority": "中"},
        ],
    },
    {
        "id": "boss07",
        "name": "孙浩",
        "age": 40,
        "city": "深圳",
        "industry": "汽车配件贸易",
        "company_size": "10人团队",
        "annual_revenue": "约500万",
        "wechat_contacts": 800,
        "keywords": ["汽车配件", "新能源汽车", "汽配", "出口", "海外市场", "B2B"],
        "network_type": "4S店+修理厂+海外买家",
        "current_goal": "开拓新能源车配件市场，进军海外",
        "pain_points": ["传统燃油车配件需求下降", "新能源配件不熟悉", "海外市场不了解"],
        "ignore_keywords": ["消费品", "餐饮", "教育"],
        "contacts": [
            {"name": "比亚迪供应商李总", "role": "新能源配件供应商", "days_since_contact": 55},
            {"name": "海外买家Mike", "role": "东南亚汽配经销商", "days_since_contact": 40},
        ],
        "today_schedule": [
            {"time": "10:00", "title": "拜访深圳某新能源汽配展商（朋友推荐）", "type": "拜访", "priority": "高"},
            {"time": "14:00", "title": "整理海外询盘报价单（3家客户）", "type": "内部任务", "priority": "高"},
            {"time": "16:30", "title": "团队周会", "type": "会议", "priority": "中"},
        ],
    },
    {
        "id": "boss08",
        "name": "吴婷",
        "age": 36,
        "city": "上海",
        "industry": "HR猎头顾问",
        "company_size": "一人公司",
        "annual_revenue": "约150万",
        "wechat_contacts": 1000,
        "keywords": ["猎头", "招聘", "人才", "AI岗位", "新能源", "高管", "中高端人才"],
        "network_type": "企业HR总监+候选人",
        "current_goal": "专攻AI/新能源行业高管猎头",
        "pain_points": ["AI行业人才稀缺但需求爆发", "候选人池不足", "企业客户开发难"],
        "ignore_keywords": ["零售", "餐饮", "制造业基层"],
        "contacts": [
            {"name": "AI公司HR王总", "role": "某AI独角兽HRVP", "days_since_contact": 25},
            {"name": "候选人张博士", "role": "AI算法专家", "days_since_contact": 14},
        ],
        "today_schedule": [
            {"time": "10:00", "title": "面试某AI公司CTO候选人（电话初面）", "type": "面试", "priority": "高"},
            {"time": "13:30", "title": "提交候选人背调报告给客户", "type": "截止日", "priority": "高"},
            {"time": "15:00", "title": "LinkedIn开发：搜索新能源行业VP候选人", "type": "开发", "priority": "中"},
            {"time": "17:00", "title": "跟进上月推荐的候选人入职情况", "type": "跟进", "priority": "低"},
        ],
    },
    {
        "id": "boss09",
        "name": "郑明",
        "age": 50,
        "city": "武汉",
        "industry": "建材经销商",
        "company_size": "15人",
        "annual_revenue": "约1200万",
        "wechat_contacts": 600,
        "keywords": ["建材", "装修", "地产", "工程", "瓷砖", "防水材料", "B2B"],
        "network_type": "开发商+装修公司+设计师",
        "current_goal": "在地产下行中找新增量，探索政府工程",
        "pain_points": ["地产下行导致需求萎缩", "账期太长资金压力大", "不知道政府工程如何切入"],
        "ignore_keywords": ["消费品", "互联网", "科技"],
        "contacts": [
            {"name": "开发商采购刘总", "role": "某地产公司采购总监", "days_since_contact": 60},
            {"name": "政府项目对接人", "role": "市政工程负责人", "days_since_contact": 90},
        ],
        "today_schedule": [
            {"time": "09:00", "title": "武汉某楼盘装修公司上门谈年度合同", "type": "拜访", "priority": "高"},
            {"time": "11:00", "title": "催款：某开发商尾款已逾期45天", "type": "财务", "priority": "高"},
            {"time": "14:00", "title": "参观政府保障房项目工地（朋友带路）", "type": "考察", "priority": "中"},
        ],
    },
    {
        "id": "boss10",
        "name": "林雪",
        "age": 31,
        "city": "北京",
        "industry": "法律科技创业公司",
        "company_size": "5人",
        "annual_revenue": "约80万（融资中）",
        "wechat_contacts": 500,
        "keywords": ["法律科技", "AI法律", "律师", "合规", "融资", "SaaS", "法律服务"],
        "network_type": "律师+投资人+法务总监",
        "current_goal": "完成天使轮融资，拓展律所客户",
        "pain_points": ["律师行业AI渗透率低", "获客困难", "投资人难接触"],
        "ignore_keywords": ["餐饮", "外贸", "制造业"],
        "contacts": [
            {"name": "投资人赵总", "role": "某早期基金合伙人", "days_since_contact": 35},
            {"name": "律所主任钱律师", "role": "北京某知名律所主任", "days_since_contact": 18},
        ],
        "today_schedule": [
            {"time": "10:00", "title": "路演：某早期基金Demo Day（15分钟上台）", "type": "路演", "priority": "高"},
            {"time": "13:00", "title": "与律所主任钱律师饭局（潜在大客户）", "type": "拜访", "priority": "高"},
            {"time": "16:00", "title": "修改融资材料——更新用户数据页", "type": "内部任务", "priority": "中"},
            {"time": "19:00", "title": "法律科技创业者聚会（VC也会来）", "type": "活动", "priority": "中"},
        ],
    },
]
