# 今日商业活动池
# 模拟从短信/邮件/微信/社交媒体自动抓取的今日可参加活动
# source: sms=短信通知, email=邮件, wechat=微信群, linkedin=领英, weibo=微博

TODAY_EVENTS = [
    {
        "id": "ev01",
        "title": "深圳AI+企业管理论坛",
        "time": "今晚 19:00-21:00",
        "location": "深圳南山区腾讯大厦B1会议厅",
        "format": "线下",
        "source": "email",
        "source_detail": "深圳企业家协会邮件通知",
        "keywords": ["AI培训", "企业管理", "HR", "组织发展"],
        "target_industries": ["企业培训", "管理咨询", "HR"],
        "description": "探讨AI时代企业管理变革，邀请100+中小企业HR总监、培训负责人出席",
        "registration_deadline": "今日17:00前扫码报名",
        "value": "高",
    },
    {
        "id": "ev02",
        "title": "上海新消费品牌策略峰会",
        "time": "今日 14:00-17:00",
        "location": "上海外滩W酒店3楼宴会厅",
        "format": "线下",
        "source": "wechat",
        "source_detail": "品牌策划师交流群",
        "keywords": ["品牌营销", "新消费", "内容策略", "私域运营"],
        "target_industries": ["品牌策划", "广告", "新消费"],
        "description": "30+新消费品牌CMO参与，聚焦2026年品牌差异化与内容创新",
        "registration_deadline": "无需预约，凭名片入场",
        "value": "高",
    },
    {
        "id": "ev03",
        "title": "广交会春季展商务对接会（预热）",
        "time": "今日 10:00-12:00",
        "location": "广州琶洲展馆旁锦江酒店",
        "format": "线下",
        "source": "sms",
        "source_detail": "广交会官方短信通知",
        "keywords": ["外贸", "广交会", "跨境电商", "东南亚", "供应链"],
        "target_industries": ["外贸", "跨境电商", "进出口"],
        "description": "广交会春季展提前对接，汇聚200+外贸企业与海外采购商，适合提前建立联系",
        "registration_deadline": "现场签到即可",
        "value": "高",
    },
    {
        "id": "ev04",
        "title": "成都互联网产品设计师沙龙",
        "time": "今晚 20:00-22:00",
        "location": "线上腾讯会议",
        "format": "线上",
        "source": "wechat",
        "source_detail": "成都设计师交流群消息",
        "keywords": ["UI设计", "产品设计", "AI工具", "用户体验"],
        "target_industries": ["UI/UX设计", "互联网", "科技"],
        "description": "成都本地产品/设计师交流会，本期主题：AI工具如何改变设计流程，已有30+人报名",
        "registration_deadline": "扫群内二维码报名",
        "value": "中",
    },
    {
        "id": "ev05",
        "title": "北京餐饮连锁经营交流会",
        "time": "今日 15:00-17:00",
        "location": "北京朝阳区某商场5楼活动中心",
        "format": "线下",
        "source": "wechat",
        "source_detail": "北京餐饮老板群",
        "keywords": ["餐饮", "连锁", "选址", "供应链", "预制菜"],
        "target_industries": ["餐饮", "食品", "连锁经营"],
        "description": "北京餐饮同行交流，重点讨论商场选址谈判技巧和预制菜供应链优化，主办方有10+商场招商资源",
        "registration_deadline": "今日13:00前回复群主确认",
        "value": "高",
    },
    {
        "id": "ev06",
        "title": "抖音电商卖家直播运营实战课",
        "time": "今日 10:00-12:00",
        "location": "线上直播",
        "format": "线上",
        "source": "sms",
        "source_detail": "抖音服务商短信推送",
        "keywords": ["抖音自播", "直播电商", "流量", "投流", "选款"],
        "target_industries": ["电商", "直播带货", "女装"],
        "description": "抖音官方合作服务商主办，讲解自播起号策略和精准投流技巧，限200人",
        "registration_deadline": "已开放，点击短信链接即可加入",
        "value": "高",
    },
    {
        "id": "ev07",
        "title": "深圳新能源汽配行业交流晚宴",
        "time": "今晚 18:30-21:00",
        "location": "深圳福田区某酒店",
        "format": "线下",
        "source": "wechat",
        "source_detail": "新能源汽配行业群",
        "keywords": ["新能源汽车", "汽配", "出口", "B2B", "海外市场"],
        "target_industries": ["汽车配件", "新能源", "汽配贸易"],
        "description": "比亚迪、宁德时代配套供应商圈子聚会，重点聊新能源配件出海机会，约50人规模",
        "registration_deadline": "需群主推荐入场",
        "value": "高",
    },
    {
        "id": "ev08",
        "title": "上海AI+人才招聘趋势论坛",
        "time": "今日 14:00-16:30",
        "location": "上海张江某联合办公空间",
        "format": "线下",
        "source": "linkedin",
        "source_detail": "LinkedIn活动推送",
        "keywords": ["猎头", "招聘", "AI岗位", "人才", "新能源", "高管"],
        "target_industries": ["HR", "猎头", "人才服务"],
        "description": "聚焦AI/新能源行业人才市场，20+企业HR总监出席，适合猎头顾问开发客户资源",
        "registration_deadline": "LinkedIn报名，今日12:00截止",
        "value": "高",
    },
    {
        "id": "ev09",
        "title": "武汉建材与工程采购对接会",
        "time": "今日 09:30-11:30",
        "location": "武汉汉口某展览中心",
        "format": "线下",
        "source": "email",
        "source_detail": "武汉市建设工程协会邮件",
        "keywords": ["建材", "工程", "政府项目", "装修", "B2B"],
        "target_industries": ["建材", "装修", "工程"],
        "description": "武汉市政工程采购方与供应商对接，重点推介保障房和市政项目材料采购需求",
        "registration_deadline": "凭营业执照复印件现场报名",
        "value": "高",
    },
    {
        "id": "ev10",
        "title": "北京法律科技创业Demo Day",
        "time": "今日 14:00-18:00",
        "location": "北京中关村某孵化器",
        "format": "线下",
        "source": "email",
        "source_detail": "法律科技创业社群邮件",
        "keywords": ["法律科技", "AI法律", "融资", "SaaS", "投资人"],
        "target_industries": ["法律科技", "LegalTech", "SaaS"],
        "description": "10家法律科技创业公司路演，20+早期投资人在场，法律行业数字化转型圆桌讨论",
        "registration_deadline": "已报名确认，今日携带BP参加",
        "value": "高",
    },
    {
        "id": "ev11",
        "title": "跨境电商卖家出海沙龙（东南亚专场）",
        "time": "今晚 19:30-21:30",
        "location": "广州天河区创业咖啡",
        "format": "线下",
        "source": "wechat",
        "source_detail": "跨境卖家交流群",
        "keywords": ["跨境电商", "东南亚", "外贸", "海外市场", "供应链"],
        "target_industries": ["外贸", "跨境电商", "汽配出口"],
        "description": "专注东南亚市场的卖家交流，分享越南、印尼、泰国市场实操经验，有海外买家代表出席",
        "registration_deadline": "扫群内码报名，名额30人",
        "value": "中",
    },
    {
        "id": "ev12",
        "title": "品牌主理人私董会（上海）",
        "time": "今晚 18:30-21:00",
        "location": "上海静安区某私人会所",
        "format": "线下",
        "source": "wechat",
        "source_detail": "品牌主理人私董会群",
        "keywords": ["品牌营销", "新消费", "私域运营", "内容策略"],
        "target_industries": ["品牌策划", "新消费", "广告"],
        "description": "仅限受邀品牌主理人和顾问参与，本期议题：2026年消费者注意力争夺战策略",
        "registration_deadline": "需群主确认资质",
        "value": "中",
    },
]