"""Official exhibition center sources used to enrich event schedules."""

from __future__ import annotations

OFFICIAL_EXHIBITION_CENTER_SOURCES: list[dict[str, str]] = [
    {"city": "北京", "center": "中国国际展览中心（老馆）", "site": "http://www.ciec-expo.com/"},
    {"city": "北京", "center": "中国国际展览中心（新馆）", "site": "http://www.nciec.com.cn/"},
    {
        "city": "北京",
        "center": "北京国家会议中心",
        "site": "http://www.cnccchina.com/",
        "schedule_url": "https://wxcncc.cnccchina.com/about/exhibition.html",
    },
    {"city": "北京", "center": "北京全国农业展览馆", "site": "http://www.ciae.com.cn/"},
    {"city": "北京", "center": "北京展览馆", "site": "http://www.bjexpo.com/"},
    {"city": "北京", "center": "中国国际贸易中心", "site": "http://www.cwtc.com/"},
    {"city": "北京", "center": "中国国家博物馆", "site": "http://www.chnmuseum.cn/"},
    {"city": "北京", "center": "中国人民革命军事博物馆", "site": "http://www.junbo.mil.cn/"},
    {"city": "北京", "center": "中国科学技术馆", "site": "http://www.cstm.org.cn/"},
    {"city": "北京", "center": "首都博物馆", "site": "http://www.capitalmuseum.org.cn/"},
    {"city": "北京", "center": "中国美术馆", "site": "http://www.namoc.org/"},
    {"city": "北京", "center": "北京市规划展览馆", "site": "http://www.bjghzl.com.cn/"},
    {"city": "北京", "center": "北京自然博物馆", "site": "http://www.bmnh.org.cn/"},
    {"city": "北京", "center": "中国地质博物馆", "site": "http://www.gmc.org.cn/"},
    {"city": "北京", "center": "中国印刷博物馆", "site": "http://www.chnpm.org/"},
    {"city": "北京", "center": "中国紫檀博物馆", "site": "http://www.redsandalwood.com/"},
    {
        "city": "上海",
        "center": "国家会展中心（上海）",
        "site": "http://www.cecsh.com/",
        "schedule_url": "https://www.neccsh.com/cecsh/exhibitioninfo/exhibitionlist.jspx",
    },
    {"city": "上海", "center": "上海新国际博览中心", "site": "http://www.sniec.net/"},
    {"city": "上海", "center": "上海世博展览馆", "site": "http://www.shexpocenter.com/"},
    {"city": "上海", "center": "上海光大会展中心", "site": "http://www.ebexhibition.com/"},
    {"city": "上海", "center": "上海国际展览中心", "site": "http://www.intex-sh.com/"},
    {"city": "上海", "center": "上海展览中心", "site": "http://www.shzlzx.com.cn/"},
    {"city": "上海", "center": "上海跨国采购会展中心", "site": "http://www.shcec.net/"},
    {"city": "上海", "center": "上海世贸商城", "site": "http://www.shanghaimart.com/"},
    {"city": "上海", "center": "上海科技馆", "site": "http://www.sstm.org.cn/"},
    {"city": "上海", "center": "上海博物馆", "site": "http://www.shanghaimuseum.net/"},
    {"city": "上海", "center": "上海自然博物馆", "site": "http://www.snhm.org.cn/"},
    {"city": "上海", "center": "上海农业展览馆", "site": "http://www.shnzg.cn/"},
    {"city": "上海", "center": "上海国际会议中心", "site": "http://www.shicc.net/"},
    {"city": "上海", "center": "上海市体育宫", "site": "http://www.shstyg.com/"},
    {"city": "上海", "center": "上海美术馆", "site": "http://shanghaimeiguan.meishujia.cn/"},
    {"city": "天津", "center": "国家会展中心（天津）", "site": "http://www.ncec.cc/"},
    {"city": "天津", "center": "天津梅江国际会展中心", "site": "http://www.mjcec.com/"},
    {"city": "天津", "center": "天津国际展览中心", "site": "http://www.tjexh.com/"},
    {"city": "天津", "center": "天津滨海国际会展中心", "site": "http://www.bicec.com.cn/"},
    {"city": "天津", "center": "天津博物馆", "site": "http://www.tjbwg.com/"},
    {"city": "重庆", "center": "重庆国际博览中心", "site": "http://www.chongqingexpo.com/"},
    {"city": "重庆", "center": "重庆展览中心", "site": "http://www.super-e.com.cn/"},
    {"city": "广州", "center": "中国进出口商品交易会展馆", "site": "http://www.ciefc.com/"},
    {"city": "深圳", "center": "深圳会展中心", "site": "http://www.szcec.com/"},
    {"city": "深圳", "center": "深圳国际会展中心（宝安）", "site": "https://www.shenzhen-world.com/"},
    {"city": "杭州", "center": "杭州国际博览中心", "site": "http://www.hzggzw.com/"},
    {"city": "杭州", "center": "杭州市国际会展中心", "site": "http://www.hiechangzhou.com/"},
    {"city": "杭州", "center": "杭州和平国际会展中心", "site": "http://www.hzpiec.com/"},
    {"city": "杭州", "center": "浙江世贸国际展览中心", "site": "http://www.expo-zj.com/"},
    {"city": "南京", "center": "南京国际博览中心", "site": "http://www.nanjingexpo.com.cn/"},
    {"city": "南京", "center": "南京国际展览中心", "site": "http://www.njiec.com/"},
    {"city": "苏州", "center": "苏州国际博览中心", "site": "http://www.suzhouexpo.com/"},
    {"city": "苏州", "center": "昆山国际会展中心", "site": "http://www.kscec.com/"},
    {"city": "苏州", "center": "花桥国际博览中心", "site": "http://www.huaqiaoexpo.com/"},
    {"city": "无锡", "center": "无锡太湖国际博览中心", "site": "http://www.wuxiexpo.com/"},
    {"city": "宁波", "center": "宁波国际会展中心", "site": "http://www.expo-nb.com/"},
    {"city": "宁波", "center": "慈溪会展中心", "site": "http://www.intex-cx.com/"},
    {"city": "温州", "center": "温州国际会展中心", "site": "http://www.wzicec.com/"},
    {"city": "温州", "center": "温州博物馆", "site": "http://www.wzmuseum.cn/"},
    {"city": "义乌", "center": "义乌国际博览中心", "site": "http://www.cccec-expo.com/"},
    {"city": "台州", "center": "台州市国际会展中心", "site": "http://www.tzicec.com/"},
    {"city": "嘉兴", "center": "嘉兴国际会展中心", "site": "http://www.jxicec.com/"},
    {"city": "青岛", "center": "青岛国际会展中心", "site": "http://www.qdicec.com.cn/"},
    {"city": "青岛", "center": "青岛国际博览中心", "site": "http://www.qingdaoiec.com/"},
    {"city": "烟台", "center": "烟台国际博览中心", "site": "http://www.ytiec.com.cn/"},
    {"city": "潍坊", "center": "潍坊富华国际展览中心", "site": "http://www.wffiec.com/"},
    {"city": "威海", "center": "威海国际会展中心", "site": "http://www.whintex.com/"},
    {"city": "廊坊", "center": "廊坊国际会议展览中心", "site": "http://www.lfgz.com/"},
    {"city": "沧州", "center": "沧州国际会展中心", "site": "http://www.czgjhzzx.com/"},
    {"city": "唐山", "center": "唐山国际会展中心", "site": "http://www.tsgjhzzx.com/"},
    {"city": "石家庄", "center": "河北省博物馆", "site": "http://www.hebeimuseum.org/"},
    {"city": "山西", "center": "山西国际博览中心", "site": "http://www.sxicec.com/"},
    {"city": "山西", "center": "中国煤炭博物馆", "site": "http://www.coalmus.cn/"},
    {"city": "山西", "center": "山西省科学技术馆", "site": "http://www.sxstm.cn/"},
    {"city": "内蒙古", "center": "内蒙古国际会展中心", "site": "http://www.nmghzzx.com/"},
    {"city": "内蒙古", "center": "赤峰国际会展中心", "site": "http://www.cficec.com/"},
    {"city": "四川", "center": "中国西部国际博览城", "site": "http://www.wciexpo.com/"},
    {"city": "湖北", "center": "武汉国际会展中心", "site": "http://www.whicec.com/"},
    {"city": "大连", "center": "大连世界博览广场", "site": "http://www.dl-worldexpo.com/"},
    {"city": "沈阳", "center": "沈阳国际展览中心", "site": "http://www.syexpo.com/"},
    {"city": "哈尔滨", "center": "哈尔滨国际会展体育中心", "site": "http://www.hrbhzzx.com/"},
    {"city": "长春", "center": "长春国际会展中心", "site": "http://www.cccen.com/"},
    {"city": "郑州", "center": "郑州国际会展中心", "site": "http://www.zziec.com/"},
    {"city": "湖南", "center": "湖南国际会展中心", "site": "http://www.hn-iec.com/"},
    {"city": "厦门", "center": "厦门国际会展中心", "site": "http://www.xicec.com/"},
    {"city": "福州", "center": "福州海峡国际会展中心", "site": "http://www.fzicec.com/"},
    {"city": "南宁", "center": "南宁国际会展中心", "site": "http://www.nicec.cn/"},
    {"city": "海南", "center": "海南国际会展中心", "site": "http://www.hncec.com/"},
    {"city": "昆明", "center": "昆明国际会展中心", "site": "http://www.kmicec.com/"},
    {"city": "贵阳", "center": "贵阳国际会议展览中心", "site": "http://www.gicec.cn/"},
    {"city": "甘肃", "center": "甘肃国际会展中心", "site": "http://www.gsicec.com/"},
    {"city": "银川", "center": "银川国际会展中心", "site": "http://www.ycexpo.com/"},
    {"city": "新疆", "center": "新疆国际会展中心", "site": "http://www.xjicec.com/"},
    {"city": "香港", "center": "香港会议展览中心", "site": "https://www.hkcec.com/"},
    {"city": "澳门", "center": "澳门威尼斯人会展中心", "site": "https://www.venetianmacao.com/"},
]
